version: 0.2
phases:
    build:
        commands:
            - echo Entered the buil phase...
            - mvn clean package
    post_build:
        commands:
            - echo Build completed successfully
artifacts:
    files:
        - target/njangui-pro.jar
    discard-paths: yes